language: c
dist: bionic

before_install:
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get install -q postgresql-server-dev-12 libcunit1-dev valgrind
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++
  - export CXX="g++"
  - sh .install-lazperf.sh
  - npm install -g eclint@1.1.5

addons:
  postgresql: "12" # for "installcheck"
  apt:
    packages:
      - postgresql-12-postgis-3

# Note: Valgrind currently reports many problems when libght is enabled. So for
# now, and until the problems are fixed, we just run the unit tests with libght
# enabled.

script:
  - eclint check * */* */cunit/*
  - ./tools/build-install.sh # test compilation without lazperf
  - ./tools/build-install.sh --with-lazperf=/usr/local && make check && ./tools/valgrind.sh
  - make installcheck || { cat pgsql/regression.diffs && false; }
  - (cd tools/benchmark_compression && sh compression_benchmark.sh)
